SchoolPortal.Web/Models/Entities/SchoolFees.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolPortal.Web.Models.Entities
{
    public class SchoolFees
    {
        public int Id { get; set; }

        [Display(Name = "SCHOOL FEES CATEGORY")]
        public string Category { get; set; }

        [Display(Name = "TOTAL AMOUNT")]
        public string Amount { get; set; }

        [Display(Name = "DISCOUNT")]
        public string Discount { get; set; }

        [Display(Name = "AMOUNT DUE")]
        public string AmountDue { get; set; }

        public int EnrolmentId { get; set; }

        public int? SessionId { get; set; }
        public Session Session { get; set; }
    }
}

SchoolPortal.Web/Areas/Admin/Controllers/SchoolFeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using SchoolPortal.Web.Areas.Data.IServices;
using SchoolPortal.Web.Areas.Data.Services;
using SchoolPortal.Web.Models;
using SchoolPortal.Web.Models.Entities;

namespace SchoolPortal.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class SchoolFeesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ISchoolFeeService _schoolFeeService = new SchoolFeeService();
        private ISessionService _sessionService = new SessionService();


        public SchoolFeesController()
        {

        }
        public SchoolFeesController(SchoolFeeService schoolFeeService, SessionService sessionService)
        {
            _schoolFeeService = schoolFeeService;
            _sessionService = sessionService;

        }
        // GET: Admin/ SchoolAccounts
        public async Task<ActionResult> Index()
        {
            var items = await _schoolFeeService.List();
            return View(items);
        }

        // GET: Admin/SchoolAccounts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fee = await _schoolFeeService.Get(id);
            if (fee == null)
            {
                return HttpNotFound();
            }
            return View(fee);
        }

        // GET: Admin/SchoolAccounts/Create
        public async Task<ActionResult> Create()
        {
            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session, "Id", "FullSession");
            return View();
        }

        // POST: Admin/SchoolAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(SchoolFees fee)
        {
            if (ModelState.IsValid)
            {
                await _schoolFeeService.Create(fee);

                return RedirectToAction("Index");
            }


            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session, "Id", "FullSession",fee.SessionId);
            return View(fee);
        }

        // GET: Admin/SchoolAccounts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fee = await _schoolFeeService.Get(id);
            if (fee == null)
            {
                return HttpNotFound();
            }
            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session, "Id", "FullSession", fee.SessionId);
            return View(fee);
        }

        // POST: Admin/SchoolAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(SchoolFees fee)
        {
            if (ModelState.IsValid)
            {
                await _schoolFeeService.Edit(fee);
                return RedirectToAction("Index");
            }
            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session, "Id", "FullSession", fee.SessionId);
            return View(fee);
        }

        // GET: Admin/SchoolAccounts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var acct = await _schoolFeeService.Get(id);
            if (acct == null)
            {
                return HttpNotFound();
            }

            return View(acct);
        }

        // POST: Admin/SchoolAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _schoolFeeService.Delete(id);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolPortal.Web/Areas/Admin/Views/SchoolFees/Create.cshtml
@model SchoolPortal.Web.Models.Entities.SchoolFees

@{
    ViewBag.Title = "Create";
}
<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">New School Fee</h3>
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong><h2><b> Note:- Select the Session and Term Result, that you want this information to display</b> </h2></strong>
                </div>
                @if (TempData["error"] != null)
                {
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["error"]
                    </div>
                }
            </div>
            @using (Html.BeginForm("Create", "SchoolFees", null, FormMethod.Post, new { id = "", enctype = "multipart/form-data" }))
            {
                @*@Html.AntiForgeryToken()*@

            <div class="box-body">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @*<div class="form-group">
            @Html.LabelFor(model => model.SessionId, "Session", htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("SessionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SessionId, "", new { @class = "text-danger" })
            </div>
        </div>*@

                <div class="form-group">
                    Select Session
                    <div class="">
                        @Html.DropDownList("SessionId", ViewBag.sessionId as SelectList, "choose a session", htmlAttributes: new { @class = "form-control", required = "Choose a session" })


                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.AmountDue, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.AmountDue, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AmountDue, "", new { @class = "text-danger" })
                    </div>
                </div>


            </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>


@section Style {

    <link rel="stylesheet" href="http://v1.exwhyzee.ng/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
}

@section Scripts {
    <!-- DataTables -->
        
    <script src="http://v1.exwhyzee.ng/admin/bower_components/ckeditor/ckeditor.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="http://v1.exwhyzee.ng/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

}

@section Scripts2 {
    <script src="http://v1.exwhyzee.ng/admin/tinymce/js/tinymce/tinymce.min.js"></script>
    @*<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>*@
    <script>
        tinymce.init({
            selector: '#mytextarea'
        });
    </script>
    @*<script>
            $(function () {
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace('editor1')
                //bootstrap WYSIHTML5 - text editor
                $('.textarea').wysihtml5()
            })
        </script>*@
}

SchoolPortal.Web/Areas/Admin/Views/SchoolFees/Delete.cshtml
@model SchoolPortal.Web.Models.Entities.SchoolFees

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="box box-default">
            <div class="box-header with-border">
                <i class="fa fa-warning"></i>

                <h3 class="box-title">Delete School Fee</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="alert alert-danger alert-dismissible">

                    <h4>
                        <i class="icon fa fa-ban"></i> Alert! Are you sure you want to delete this?
                    </h4>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Category)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Category)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Amount)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Amount)
                        </dd>

                    </dl>
                    @using (Html.BeginForm())
                    {
                        @*@Html.AntiForgeryToken()*@

                        <div class="form-actions no-color btn-delete">
                            <input type="submit" value="Delete" class="btn btn-default" /> &nbsp;
                            <a href="javascript: history.back()" class="btn btn-default">Cancel</a>

                        </div>
                    }


                </div>

            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->


    <div class="col-md-3"></div>

</div>

SchoolPortal.Web/Areas/Admin/Views/SchoolFees/Details.cshtml
@model SchoolPortal.Web.Models.Entities.SchoolFees

@{
    ViewBag.Title = "Details";
}


<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="box box-default">
            <div class="box-header with-border">

                <h3 class="box-title">Details of School Fee </h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Category)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Category)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Amount)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Amount)
                    </dd>


                    <dt>
                        @Html.DisplayNameFor(model => model.Discount)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Discount)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.AmountDue)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.AmountDue)
                    </dd>


                   

                </dl>

            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->


    <div class="col-md-3"></div>

</div>

SchoolPortal.Web/Areas/Admin/Views/SchoolFees/Edit.cshtml
@model SchoolPortal.Web.Models.Entities.SchoolFees

@{
    ViewBag.Title = "Edit";
}



<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Edit School Fee</h3>
                @if (TempData["error"] != null)
                {
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["error"]
                    </div>
                }
            </div>
            @using (Html.BeginForm("Edit", "SchoolFees", null, FormMethod.Post, new { id = "", enctype = "multipart/form-data" }))
            {
                @*@Html.AntiForgeryToken()*@

            <div class="box-body">

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Id)


                @*<div class="form-group">
            @Html.LabelFor(model => model.SessionId, "Session", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SessionId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SessionId, "", new { @class = "text-danger" })
            </div>
        </div>*@

                <div class="form-group">
                    Select Session
                    <div class="">
                        @Html.DropDownList("SessionId", ViewBag.sessionId as SelectList, "choose a session", htmlAttributes: new { @class = "form-control", required = "Choose a session" })


                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.AmountDue, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.AmountDue, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.AmountDue, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>

@section Style {

    <link rel="stylesheet" href="http://v1.exwhyzee.ng/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">
}

@section Scripts {
    <!-- DataTables -->
    <script src="http://v1.exwhyzee.ng/admin/bower_components/ckeditor/ckeditor.js"></script>
    <!-- Bootstrap WYSIHTML5 -->
    <script src="http://v1.exwhyzee.ng/admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>

}

@section Scripts2 {

    <script src="http://v1.exwhyzee.ng/admin/tinymce/js/tinymce/tinymce.min.js"></script>
    @*<script src='https://cloud.tinymce.com/stable/tinymce.min.js'></script>*@
    <script>
        tinymce.init({
            selector: '#mytextarea'
        });
    </script>
    @*<script>
            $(function () {
                // Replace the <textarea id="editor1"> with a CKEditor
                // instance, using default configuration.
                CKEDITOR.replace('editor1')
                //bootstrap WYSIHTML5 - text editor
                $('.textarea').wysihtml5()
            })
        </script>*@
}

SchoolPortal.Web/Areas/Admin/Views/SchoolFees/Index.cshtml
@model IEnumerable<SchoolPortal.Web.Models.Entities.SchoolFees>

@{
    ViewBag.Title = "Index";
}


<div class="row">
    <div class="col-xs-12">
        <div class="box" style="padding:7px;">
            <div class="box-header" style="margin-bottom:15px;">
                <h3 class="box-title"><i class="fa fa-fw fa-file-text-o"></i> School Fees Management</h3>

                <div class="box-tools">
                    @Html.ActionLink("New Fee", "Create", null, new { @class = "btn btn-primary", style = "padding: 7px;" })
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table id="example1" class="table table-bordered table-hover" border="1">

                    <thead>
                        <tr>
                            <th>S/N</th>
                            <th>
                                Session
                            </th>
                            <th>
                                Category
                            </th>
                            <th>
                                Amount
                            </th>
                            <th>
                                Discount
                            </th>
                            <th> Amount Due</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int sno = 0;
                        }
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @{ sno++; }
                                @sno
                            </td>
                            <td>
                                @item.Session.SessionYear - @item.Session.Term Term
                            </td>
                           
                            <td>
                                @item.Category

                            </td>
                            <td>
                                @item.Amount
                            </td>
                            <td>
                                @item.Discount
                            </td>
                            <td>
                                @item.AmountDue
                            </td>
                            <td>

                                <div class="dropdown">
                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                        Action
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu">

                                        <li class="text-color-warning">@Html.ActionLink("Edit", "Edit", new { id = item.Id }, null)</li>
                                        <li class="text-color-success">@Html.ActionLink("Details", "Details", new { id = item.Id }, null)</li>

                                        <li class="text-color-danger">@Html.ActionLink("Delete", "Delete", new { id = item.Id }, null)</li>

                                    </ul>
                                </div>

                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>


    @section Style {

        <link rel="stylesheet" href="http://v1.exwhyzee.ng/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">

    }

    @section Scripts {
        <!-- DataTables -->
        <script src="http://v1.exwhyzee.ng/admin/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
        <script src="http://v1.exwhyzee.ng/admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    }

    @section Scripts2 {
        <script>
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
        </script>
    }

</div>