SchoolPortal.Web/Models/Entities/BatchResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SchoolPortal.Web.Models.Entities
{
    public class BatchResult
    {
        public int Id { get; set; }
        public string BatchId { get; set; }
        public string StudentRegNumber { get; set; }
        public int ProfileId { get; set; }
        public int SessionId { get; set; }
        public int ClassId { get; set; }
        public int EnrollmentId { get; set; }
        public decimal? AverageScore { get; set; }
    }
}

SchoolPortal.Web/Models/Entities/ResultViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolPortal.Web.Models.Entities
{
    public class ResultViewModel
    {
        [Required(ErrorMessage="PIN Number is a required field")]
        [Display(Name="PIN Number")]
        public string PinNumber { get; set; }

        [Required(ErrorMessage = "Serial Number is a required field")]
        [Display(Name = "Serial Number")]
        public string SerialNumber { get; set; }
    }
}

SchoolPortal.Web/Models/Entities/SchoolFees.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SchoolPortal.Web.Models.Entities
{
    public class SchoolFees
    {
        public int Id { get; set; }

        [Display(Name = "SCHOOL FEES CATEGORY")]
        public string Category { get; set; }

        [Display(Name = "TOTAL AMOUNT")]
        public string Amount { get; set; }

        [Display(Name = "DISCOUNT")]
        public string Discount { get; set; }

        [Display(Name = "AMOUNT DUE")]
        public string AmountDue { get; set; }

        public int EnrolmentId { get; set; }

        public int? SessionId { get; set; }
        public Session Session { get; set; }
    }
}

SchoolPortal.Web/Areas/Admin/Controllers/ResultManagementController.cs
using SchoolPortal.Web.Areas.Data.IServices;
using SchoolPortal.Web.Areas.Data.Services;
using SchoolPortal.Web.Models;
using SchoolPortal.Web.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data;
using SchoolPortal.Web.Models.Dtos;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace SchoolPortal.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class ResultManagementController : Controller
    {
        #region services


        private ApplicationDbContext db = new ApplicationDbContext();
        private ISessionService _sessionService = new SessionService();
        private IClassLevelService _classlevelService = new ClassLevelService();
        private IPublishResultService _publishService = new PublishResultService();
        private IEnrollmentService _enrolService = new EnrollmentService();
        private IResultService _resultService = new ResultService();
        private IStudentProfileService _studentService = new StudentProfileService();
        private ISettingService _settingService = new SettingService();
        private IEnrolledSubjectService _enrolledService = new EnrolledSubjectService();


        public ResultManagementController()
        {

        }
        public ResultManagementController(
            SessionService sessionService,
            ClassLevelService classLevelService,
            PublishResultService publishService,
            ResultService resultService,
            StudentProfileService studentService,
            SettingService settingService,
            EnrolledSubjectService enrolledService,
            EnrollmentService enrolService,
            ApplicationUserManager userManager
            )
        {
            _sessionService = sessionService;
            _classlevelService = classLevelService;
            _publishService = publishService;
            _enrolService = enrolService;
            _resultService = resultService;
            _studentService = studentService;
            _settingService = settingService;
            _enrolledService = enrolledService;
            UserManager = userManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }

        #endregion
        // GET: Admin/ResultManagement
        public async Task<ActionResult> Index()
        {
            var classlevel = await _classlevelService.ClassLevelList();
            ViewBag.ClassLevelId = new SelectList(classlevel.OrderBy(x => x.ClassLevelName), "Id", "ClassLevelName");

            var session = await db.Sessions.FirstOrDefaultAsync(x => x.Status == SessionStatus.Current);
            ViewBag.sessionId = session.Id;
            ViewBag.session = session.SessionYear + " - " + session.Term + " Term";
            return View();
        }

        public async Task<ActionResult> OtherTerm()
        {
            var classlevel = await _classlevelService.ClassLevelList();
            ViewBag.ClassLevelId = new SelectList(classlevel.OrderBy(x => x.ClassLevelName), "Id", "ClassLevelName");

            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session.OrderBy(x => x.FullSession), "Id", "FullSession");
            return View();
        }

        //NEW ENROLMENT
        public async Task<ActionResult> NewEnrolment()
        {
            var classlevel = await _classlevelService.ClassLevelList();
            ViewBag.ClassLevelId = new SelectList(classlevel.OrderBy(x => x.ClassLevelName), "Id", "ClassLevelName");

            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session.OrderByDescending(x => x.FullSession), "Id", "FullSession");
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult AllStudents(int sessId, int classId)
        {
            if (sessId == null || classId == null)
            {
                TempData["error"] = "make a selection";
            }

            IQueryable<StudentProfile> user = from s in db.StudentProfiles
                                              .Include(x=>x.user)
                                               .Include(p => p.user).Where(x => x.user.Status == EntityStatus.Active)
                                               .OrderBy(x => x.user.UserName)
                                              select s;
            var classname = db.ClassLevels.FirstOrDefault(x => x.Id == classId);
            ViewBag.cname = classname.ClassName;
            var sessionname = db.Sessions.FirstOrDefault(x => x.Id == sessId);
            ViewBag.sname = sessionname.SessionYear;
            ViewBag.sessid = sessId;
            ViewBag.classid = classId;
            return View(user);
        }
        #region Batch result



        //batch print
        public async Task<ActionResult> BatchResult()
        {
             var sett = db.Settings.FirstOrDefault();
            if(sett.DisableAllResultPrinting == true)
            {
                return RedirectToAction("Verify", "Panel", new {area="Student"});
            }
            var classlevel = await _classlevelService.ClassLevelList();
            ViewBag.ClassLevelId = new SelectList(classlevel.OrderBy(x => x.ClassLevelName), "Id", "ClassLevelName");

            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session.OrderByDescending(x => x.FullSession), "Id", "FullSession");
            return View();
        }

        public async Task<ActionResult> StudentsForBatchResult(int sessId, int classId)
        {
            var enrolledStudents = await _resultService.StudentsBySessIdAndByClassId(sessId, classId);
            if (enrolledStudents.Count() <= 0)
            {
                return HttpNotFound();
            }
            //UpdateComment recognitive domain
            foreach (var abcd in enrolledStudents)
            {
                var studentsss = await db.StudentProfiles.FirstOrDefaultAsync(x => x.StudentRegNumber == abcd.StudentRegNumber);
                var check = await db.RecognitiveDomains.FirstOrDefaultAsync(x => x.EnrolmentId == abcd.EnrollmentId);
                if (check == null)
                {
                    RecognitiveDomain recognitive = new RecognitiveDomain();
                    recognitive.EnrolmentId = abcd.EnrollmentId;
                    db.RecognitiveDomains.Add(recognitive);
                    await db.SaveChangesAsync();

                    //Add Tracking
                    var userId2 = User.Identity.GetUserId();
                    var user2 = UserManager.Users.Where(x => x.Id == userId2 && x.Status == EntityStatus.Active).FirstOrDefault();
                    Tracker tracker = new Tracker();
                    tracker.UserId = userId2;
                    tracker.UserName = user2.UserName;
                    tracker.FullName = user2.Surname + " " + user2.FirstName + " " + user2.OtherName;
                    tracker.ActionDate = DateTime.UtcNow.AddHours(1);
                    tracker.Note = tracker.FullName + " " + "Updated Recognitive Domain";
                    //db.Trackers.Add(tracker);
                    await db.SaveChangesAsync();
                }

                var check2 = await db.AffectiveDomains.FirstOrDefaultAsync(x => x.EnrolmentId == abcd.EnrollmentId);
                if (check2 == null)
                {
                    AffectiveDomain affective = new AffectiveDomain();
                    affective.EnrolmentId = abcd.EnrollmentId;
                    db.AffectiveDomains.Add(affective);
                    await db.SaveChangesAsync();

                    //Add Tracking
                    var userId2 = User.Identity.GetUserId();
                    var user2 = UserManager.Users.Where(x => x.Id == userId2 && x.Status == EntityStatus.Active).FirstOrDefault();
                    Tracker tracker = new Tracker();
                    tracker.UserId = userId2;
                    tracker.UserName = user2.UserName;
                    tracker.FullName = user2.Surname + " " + user2.FirstName + " " + user2.OtherName;
                    tracker.ActionDate = DateTime.UtcNow.AddHours(1);
                    tracker.Note = tracker.FullName + " " + "Updated Affective Domain";
                    //db.Trackers.Add(tracker);
                    await db.SaveChangesAsync();
                }

                var check3 = await db.PsychomotorDomains.FirstOrDefaultAsync(x => x.EnrolmentId == abcd.EnrollmentId);
                if (check3 == null)
                {
                    PsychomotorDomain psychomotor = new PsychomotorDomain();
                    psychomotor.EnrolmentId = abcd.EnrollmentId;
                    db.PsychomotorDomains.Add(psychomotor);
                    await db.SaveChangesAsync();

                    //Add Tracking
                    var userId2 = User.Identity.GetUserId();
                    var user2 = UserManager.Users.Where(x => x.Id == userId2 && x.Status == EntityStatus.Active).FirstOrDefault();
                    Tracker tracker = new Tracker();
                    tracker.UserId = userId2;
                    tracker.UserName = user2.UserName;
                    tracker.FullName = user2.Surname + " " + user2.FirstName + " " + user2.OtherName;
                    tracker.ActionDate = DateTime.UtcNow.AddHours(1);
                    tracker.Note = tracker.FullName + " " + "Updated Psychomotor Domain";

SchoolPortal.Web/Areas/Admin/Controllers/SchoolFeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using SchoolPortal.Web.Areas.Data.IServices;
using SchoolPortal.Web.Areas.Data.Services;
using SchoolPortal.Web.Models;
using SchoolPortal.Web.Models.Entities;

namespace SchoolPortal.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class SchoolFeesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ISchoolFeeService _schoolFeeService = new SchoolFeeService();
        private ISessionService _sessionService = new SessionService();


        public SchoolFeesController()
        {

        }
        public SchoolFeesController(SchoolFeeService schoolFeeService, SessionService sessionService)
        {
            _schoolFeeService = schoolFeeService;
            _sessionService = sessionService;

        }
        // GET: Admin/ SchoolAccounts
        public async Task<ActionResult> Index()
        {
            var items = await _schoolFeeService.List();
            return View(items);
        }

        // GET: Admin/SchoolAccounts/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fee = await _schoolFeeService.Get(id);
            if (fee == null)
            {
                return HttpNotFound();
            }
            return View(fee);
        }

        // GET: Admin/SchoolAccounts/Create
        public async Task<ActionResult> Create()
        {
            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session, "Id", "FullSession");
            return View();
        }

        // POST: Admin/SchoolAccounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(SchoolFees fee)
        {
            if (ModelState.IsValid)
            {
                await _schoolFeeService.Create(fee);

                return RedirectToAction("Index");
            }


            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session, "Id", "FullSession",fee.SessionId);
            return View(fee);
        }

        // GET: Admin/SchoolAccounts/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var fee = await _schoolFeeService.Get(id);
            if (fee == null)
            {
                return HttpNotFound();
            }
            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session, "Id", "FullSession", fee.SessionId);
            return View(fee);
        }

        // POST: Admin/SchoolAccounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(SchoolFees fee)
        {
            if (ModelState.IsValid)
            {
                await _schoolFeeService.Edit(fee);
                return RedirectToAction("Index");
            }
            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session, "Id", "FullSession", fee.SessionId);
            return View(fee);
        }

        // GET: Admin/SchoolAccounts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var acct = await _schoolFeeService.Get(id);
            if (acct == null)
            {
                return HttpNotFound();
            }

            return View(acct);
        }

        // POST: Admin/SchoolAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await _schoolFeeService.Delete(id);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SchoolPortal.Web/Areas/Admin/Views/ResultManagement/AllStudents.cshtml
@model IEnumerable<SchoolPortal.Web.Models.Entities.StudentProfile>

@{
    ViewBag.Title = "AllStudents";
}

<div class="row">
    <div class="col-xs-12">
        <div class="box" style="padding:7px;">
            <div class="box-header" style="margin-bottom:15px;">
                <h3 class="box-title" style="font-weight:900;"><i class="fa fa-fw fa-file-text-o"></i> Comprehensive Student List</h3>
                <h3 class="box-title" style="font-weight:900;">Session (@ViewBag.sname)</h3>
                <h3 class="box-title" style="font-weight:900;">Class (@ViewBag.cname)</h3>

            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div class="table-responsive">
                    <table id="example1" class="table table-bordered table-hover" border="1">
                        <tr>
                            <th>S/N</th>
                            <th>Username</th>
                            <th>Full Name</th>
                            <th>Registration Number</th>
                            <th></th>
                        </tr>
                        @{int sno = 0;
                        }
                        @foreach (var students in Model)
                        {

                            <tr>
                                @{ sno++; }

                                <td>@sno</td>
                                <td>@students.user.UserName</td>
                                <td>@students.user.Surname @students.user.FirstName @students.user.OtherName</td>
                                <td>@students.StudentRegNumber</td>

                                <td>
                                   @* @Html.ActionLink("Enroll", "EnrollStudentList", "Enrollments", new { id = students.Id, ClassLevelId = ViewBag.classid, SessionId = ViewBag.sessid }, new { @class = "" })*@
                                    <a href="@Url.Action("EnrollStudentList", "Enrollments", new { id = students.Id, ClassLevelId = ViewBag.classid, SessionId = ViewBag.sessid })" target="_blank">Enroll</a>
                                    @*@using (Html.BeginForm("EnrollStudentList", "Enrollments", new { id = students.Id, ClassLevelId = ViewBag.classid, SessionId = ViewBag.sessid }, FormMethod.Post))
                                    {


                                        <button type="submit" class="btn btn-primary">Enroll </button>

                                    }*@
                                </td>

                            </tr>



                        }
                    </table>
                    <br clear="all" style="page-break-before:always !important;" />
                </div>
            </div>
        </div>
    </div>
</div>


@section Style {

    <link rel="stylesheet" href="http://v1.exwhyzee.ng/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
}

@section Scripts {
    <!-- DataTables -->
    <script src="http://v1.exwhyzee.ng/admin/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="http://v1.exwhyzee.ng/admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

}

@section Scripts2 {
    <script>
        $(function () {
            $('#example1').DataTable()
            $('#example2').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
}

SchoolPortal.Web/Areas/Admin/Views/ResultManagement/BatchResult.cshtml
@using SchoolPortal.Web.Areas.Service
@{
    ViewBag.Title = "BatchResult";

}



<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Batch Result</h3>
                @if (TempData["Error"] != null)
                {
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>@TempData["Error"]</strong>
                    </div>
                }

                @if (TempData["failure"] != null)
                {
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong>@TempData["failure"]</strong>
                    </div>
                }
            </div>
          
            @using (Html.BeginForm("StudentsForBatchResult", "ResultManagement", null, FormMethod.Post))
            {
                @*@Html.AntiForgeryToken()*@

                <div class="box-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="form-group">
                        Select Session
                        <div class="">
                            @Html.DropDownList("sessId", ViewBag.sessionId as SelectList, "choose a session", htmlAttributes: new { @class = "form-control", required = "Choose a session" })


                        </div>
                    </div>

                    <div class="form-group">
                        Select Class
                        <div class="">
                            @Html.DropDownList("classId", ViewBag.ClassLevelId as SelectList, "choose a class", htmlAttributes: new { @class = "form-control", required = "Choose a class" })


                        </div>
                    </div>

                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">View @GeneralService.StudentorPupil()<span>s</span></button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>

@section Scripts {
        
}

SchoolPortal.Web/Areas/Admin/Views/ResultManagement/CummulativeMasterListAllSessions.cshtml
@using SchoolPortal.Web.Areas.Service

@{
    ViewBag.Title = "Cummulative Master List All Sessions";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Cummulative Master List Management</h3>
                @if (TempData["msg"] != null)
                {
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["msg"]
                    </div>
                }


            </div>
            @using (Html.BeginForm("CummulativeMasterList", "ResultManagement", null, FormMethod.Post))
            {
                @*@Html.AntiForgeryToken()*@

                <div class="box-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="form-group">
                        Select Session
                        <div class="">
                            @Html.DropDownList("sessId", ViewBag.sessionId as SelectList, "choose a session", htmlAttributes: new { @class = "form-control", required = "Choose a session" })


                        </div>
                    </div>

                    <div class="form-group">
                        Select Class
                        <div class="">
                            @Html.DropDownList("classId", ViewBag.ClassLevelId as SelectList, "choose a class", htmlAttributes: new { @class = "form-control", required = "Choose a class" })


                        </div>
                    </div>

                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Show Cumm. Master List</button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>

@section Scripts {
        
}

SchoolPortal.Web/Areas/Admin/Views/ResultManagement/MasterListIndex.cshtml
@using SchoolPortal.Web.Areas.Service
@{
    ViewBag.Title = "MasterListIndex";
}


<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Master List Management</h3>
                @if (TempData["msg"] != null)
                {
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["msg"]
                    </div>
                }

          
            </div>
            @using (Html.BeginForm("MasterList", "ResultManagement", null, FormMethod.Post))
            {
                @*@Html.AntiForgeryToken()*@

                <div class="box-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="form-group">
                        Current Session @Html.ActionLink("Other Session", "MasterListAllSessions", "ResultManagement", null, new { @class = "btn btn-primary btn-sm", style = "margin-bottom:5px;" })

                        <div class="">
                            @*@Html.DropDownList("sessId", ViewBag.sessionId as SelectList, "choose a session", htmlAttributes: new { @class = "form-control", required = "Choose a session" })*@
                            <input type="hidden" name="sessId" value="@ViewBag.sessionId" class="form-control" />
                            <input type="text" value="@ViewBag.session" class="form-control" disabled="disabled" />

                        </div>
                    </div>

                    <div class="form-group">
                        Select Class
                        <div class="">
                            @Html.DropDownList("classId", ViewBag.ClassLevelId as SelectList, "choose a class", htmlAttributes: new { @class = "form-control", required = "Choose a class" })


                        </div>
                    </div>

                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Show Master List</button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>

@section Scripts {
        @**@
}

SchoolPortal.Web/Areas/Admin/Views/ResultManagement/MasterSubjects.cshtml
@model IEnumerable<SchoolPortal.Web.Models.Dtos.EnrolledStudentsByClassDto>


@using SchoolPortal.Web.Areas.Service


@foreach (var subn in ViewBag.listx)
{
    if (GeneralService.IsPrintOutThree() == true && (GeneralService.TotalStudentCAScore(ViewBag.idc) == null || GeneralService.TotalStudentCAScore(ViewBag.idc) == 0))
    {
        <td>
            @if (subn.TotalCA == 0)
            {

                if (subn.TestScore == 0)
                {
                    <text>-</text>
                }
                else
                {
                    @Math.Round(subn.TestScore ?? 0)

                }
            }
            else
            {
                @Math.Round(subn.TotalCA ?? 0)

            }
        </td>
    }
    else if (GeneralService.TotalStudentCAScore(ViewBag.idc) != null || GeneralService.TotalStudentCAScore(ViewBag.idc) != 0)
    {
        <td>
            @if (subn.TotalCA == 0)
            {
                if (subn.TestScore == 0)
                {
                    <text>-</text>
                }
                else
                {
                    @Math.Round(subn.TestScore ?? 0)

                }
            }
            else
            {
                @Math.Round(subn.TotalCA ?? 0)

            }
        </td>
    }
    else
    {
        <td>
            @if (subn.TestScore == 0)
            {
                <text> -</text>
            }
            else
            {
                @Math.Round(subn.TestScore ?? 0)

            }
        </td>
    }

    <td>
        @if (subn.ExamScore == 0)
        {
            <text>-</text>
        }
        else
        {
            @Math.Round(subn.ExamScore ?? 0)

        }

    </td>
    <td>
        @if (subn.TotalScore == 0)
        {
            <text>-</text>
        }
        else
        {
            @Math.Round(subn.TotalScore ?? 0)

        }

    </td>
}