SchoolPortal.Web/Models/Entities/LessonNote.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SchoolPortal.Web.Models.Entities
{
    public class LessonNote
    {
        public int Id { get; set; }      
        public int? SubjectId { get; set; }
        public Subject Subject { get; set; }

         public int? SessionId { get; set; }
        public Session Session { get; set; }

         public int? StaffProfileId { get; set; }
        public StaffProfile StaffProfile { get; set; }
        public string Topic { get; set; }
        [AllowHtml]
        public string Note { get; set; }
        public DateTime DateCreated { get; set; } 
        public DateTime LastEdited { get; set; } 
        public bool IsPublished { get; set; }
    }
}

SchoolPortal.Web/Areas/Content/Controllers/DocController.cs
using SchoolPortal.Web.Models;
using SchoolPortal.Web.Models.Dtos;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Threading.Tasks;
using SchoolPortal.Web.Areas.Data.IServices;
using SchoolPortal.Web.Areas.Data.Services;
using System.Net;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity.Validation;
using SchoolPortal.Web.Areas.Service;
using SchoolPortal.Web.Models.Entities;

namespace SchoolPortal.Web.Areas.Content.Controllers
{
    [Authorize(Roles = "Admin,SuperAdmin")]
    public class DocController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private IEnrollmentService _enrollmentService = new EnrollmentService();
        private IClassLevelService _classlevelService = new ClassLevelService();
        private IStudentProfileService _studentService = new StudentProfileService();
        private IUserManagerService _userService = new UserManagerService();
        private ISessionService _sessionService = new SessionService();


        public DocController()
        {

        }
        public DocController(
            EnrollmentService enrollmentService,
            SessionService sessionService,
            ClassLevelService classLevelService,
            StudentProfileService studentService,
            ApplicationUserManager userManager,
            UserManagerService userService
            )
        {
            _userService = userService;
            UserManager = userManager;
            _enrollmentService = enrollmentService;
            _classlevelService = classLevelService;
            _studentService = studentService;
            _sessionService = sessionService;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }
        // GET: Content/Doc
        public ActionResult Index()
        {
            var item = db.ClassLevels.Include(x => x.User).Where(x=>x.ShowClass == true).ToList();
            var output = item.Select(x => new ClassLevelListDto
            {
                ClassLevelName = x.ClassName,
                Id = x.Id,
                userId = x.UserId,
                FormTeacher = x.User.Surname + " " + x.User.FirstName + " " + x.User.OtherName
            });


            return View(output.OrderBy(x => x.ClassLevelName).ToList());
        }
        public async Task<ActionResult> LessonNote()
        {

            var note = await db.LessonNotes.Include(x => x.Subject).Include(x => x.Subject.ClassLevel).Include(x => x.StaffProfile).Include(x => x.Session).Where(x => x.IsPublished == true).ToListAsync();

            return View(note);
        }

        public async Task<ActionResult> LessonNoteDetail(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = await db.LessonNotes.Include(x => x.Session).Include(x => x.Subject).Include(x => x.Subject.ClassLevel).FirstOrDefaultAsync(x => x.Id == id);

            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }
        public ActionResult StudentsList()
        {
            var item = db.ClassLevels.Include(x => x.User).Where(x => x.ClassName.Contains("JSS")).ToList();
            var output = item.Select(x => new ClassLevelListDto
            {
                ClassLevelName = x.ClassName,
                Id = x.Id,
                userId = x.UserId,
                FormTeacher = x.User.Surname + " " + x.User.FirstName + " " + x.User.OtherName
            });


            return View(output.OrderBy(x => x.ClassLevelName).ToList());
        }
        public async Task<ActionResult> IndexForList()
        {
            //var classlevel = await _classlevelService.ClassLevelList();
            //ViewBag.ClassLevelId = new SelectList(classlevel.OrderBy(x => x.ClassLevelName), "Id", "ClassLevelName");

            //var session = await db.Sessions.FirstOrDefaultAsync(x => x.Status == SessionStatus.Current);
            //ViewBag.sessionId = session.Id;
            //ViewBag.session = session.SessionYear + " - " + session.Term + " Term";
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> EnrolFromSession(int sessionId)
        {

            try
            {
                var session = db.Sessions.FirstOrDefault(x => x.Id == sessionId);
                var enrolment = db.Enrollments.Where(x => x.SessionId == session.Id).ToList();
                foreach (var x in enrolment)
                {
                    await _enrollmentService.EnrollStudentFromSession(x.ClassLevelId ?? 0, x.StudentProfileId, sessionId);
                }



            }
            catch (Exception e)
            {
                TempData["error"] = "Enrollment was not successfull. Please try again.";
                return RedirectToAction("Index");
            }
            return RedirectToAction("OtherTerm");
        }
        public async Task<ActionResult> Dropout(int id = 0)
        {

            try
            {
                var item = await _enrollmentService.ChangeToDropoutStudent(id);

                return RedirectToAction("Success", new { result = item });


            }
            catch (Exception ex)
            {
                return RedirectToAction("Success", new { result = "Unable to Update" });

            }

        }
        public ActionResult Success(string result)
        {
            if (result == "successfully")
            {
                TempData["success"] = "Updated successfully";
            }
            else
            {
                TempData["error"] = "Unable to Update";
            }

            return View();
        }
        [HttpPost]
        public ActionResult IndexBySession(int sessionId)
        {
            var item = db.ClassLevels.Include(x => x.User).ToList();
            var output = item.Select(x => new ClassLevelListDto
            {
                ClassLevelName = x.ClassName,
                Id = x.Id,
                userId = x.UserId,
                FormTeacher = x.User.Surname + " " + x.User.FirstName + " " + x.User.OtherName
            });
            ViewBag.sId = sessionId;
            var xy = db.Sessions.Find(sessionId);
            ViewBag.sname = xy.SessionYear + " - " + xy.Term + " Term";
            return View(output.OrderBy(x => x.ClassLevelName).ToList());
        }

        public async Task<ActionResult> OtherTerm()
        {

            var session = await _sessionService.GetAllSession();
            ViewBag.sessionId = new SelectList(session.OrderBy(x => x.FullSession), "Id", "FullSession");
            return View();
        }
        ///get the student in a particular session
        ///
        public async Task<ActionResult> StudentsInTerm(int? sessionId)
        {
            try
            {


                var session = await db.Sessions.ToListAsync();
                var sessionoutput = session.Select(x => new SchoolSessionDto
                {
                    Id = x.Id,
                    FullSession = x.SessionYear + " " + x.Term

                });
                ViewBag.sessionId = new SelectList(sessionoutput, "Id", "FullSession");

                ViewBag.session = sessionId;

                var item = db.ClassLevels.Include(x => x.User).ToList();
                var output = item.Select(x => new ClassLevelListDto
                {
                    ClassLevelName = x.ClassName,
                    Id = x.Id,
                    userId = x.UserId,
                    FormTeacher = x.User.Surname + " " + x.User.FirstName + " " + x.User.OtherName
                });
                return View(output.OrderBy(x => x.ClassLevelName).ToList());
            }
            catch (Exception e)
            {
                return RedirectToAction("StudentsInTerm");
            }
        }



        /// <summary>
        public ActionResult ResultSummary()
        {
            var item = db.ClassLevels.Include(x => x.User).ToList();
            var output = item.Select(x => new ClassLevelListDto
            {
                ClassLevelName = x.ClassName,
                Id = x.Id,
                userId = x.UserId,
                FormTeacher = x.User.Surname + " " + x.User.FirstName + " " + x.User.OtherName
            });
            return View(output.OrderBy(x => x.ClassLevelName).ToList());
        }

        public ActionResult IndexAllByClass()
        {
            var item = db.ClassLevels.Include(x => x.User).ToList();
            var output = item.Select(x => new ClassLevelListDto
            {
                ClassLevelName = x.ClassName,
                Id = x.Id,
                userId = x.UserId,
                FormTeacher = x.User.Surname + " " + x.User.FirstName + " " + x.User.OtherName
            });


            return View(output.OrderBy(x => x.ClassLevelName).ToList());
        }

        /// <summary>
        /// /
        /// </summary>
        /// <returns></returns>
        /// 


        public async Task<ActionResult> IndexByEnrolId()
        {
            var session = await db.Sessions.FirstOrDefaultAsync(x => x.Status == Models.Entities.SessionStatus.Current);
            var enr = await db.Enrollments.Include(x => x.ClassLevel).Include(x => x.Session).Include(x => x.User).Include(x => x.StudentProfile).Include(x => x.StudentProfile.user).Where(x => x.Session.SessionYear == session.SessionYear).OrderBy(x => x.Id).ToListAsync();
            return View(enr);

        }


        /////
        ///

SchoolPortal.Web/Areas/Content/Views/Doc/EnrollFromAnotherTermInSession.cshtml
 
@using SchoolPortal.Web.Areas.Service

@{
    ViewBag.Title = "EnrollFromAnotherTermInSession";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">EnrollFromAnotherTermInSession</h3>
                @if (TempData["msg"] != null)
                {
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["msg"]
                    </div>
                }
            </div>
            @using (Html.BeginForm("EnrollFromAnotherTermInSession", "Doc", null, FormMethod.Post))
            {
                @*@Html.AntiForgeryToken()*@

                <div class="box-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <div class="form-group">
                        Select Session
                        <div class="">
                            @Html.DropDownList("sessId", ViewBag.sessionId as SelectList, "choose a session", htmlAttributes: new { @class = "form-control", required = "Choose a session" })
                        </div>
                    </div>

                   
                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Enroll Them</button>

                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>

@section Scripts {
    @**@
}

SchoolPortal.Web/Areas/Content/Views/Doc/EnrollmentWithScore.cshtml
@model SchoolPortal.Web.Models.Entities.Enrollment
@using SchoolPortal.Web.Areas.Service

@{
    ViewBag.Title = "Enrollment With Score";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}



<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">@GeneralService.StudentorPupil() Has Score</h3>
                @if (TempData["error"] != null)
                {
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["error"]
                    </div>
                }
            </div>
         
                <div class="box-body">

                    <table class="table table-bordered table-hover" border="1">
                        <tr>
                            <th>Full Name</th>
                            <td>@Model.StudentProfile.user.Surname @Model.StudentProfile.user.FirstName @Model.StudentProfile.user.OtherName </td>
                        </tr>
                        <tr>
                            <th>Registration Number</th>
                            <td>@Model.StudentProfile.StudentRegNumber</td>
                        </tr>
                        <tr>
                            <th>Session</th>
                            <td>@Model.Session.SessionYear - @Model.Session.Term</td>
                        </tr>
                        <tr>
                            <th>Class</th>
                            <td>@Model.ClassLevel.ClassName</td>
                        </tr>
                        <tr>
                            <th>Average Score</th>
                            <td>@Model.AverageScore</td>
                        </tr>

                        <tr>
                            <th>Cum. Score</th>
                            <td>@Model.CummulativeAverageScore</td>
                        </tr>

                    </table>
                </div>

                <div class="box-footer">
                    @Html.ActionLink("Continue to Remove " + GeneralService.StudentorPupil(), "RemoveWithScore", "Doc", new { id = Model.StudentProfileId }, new { @class = "btn btn-info" })

                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            
        </div>

    </div>
    <div class="col-md-3"></div>

</div>

@section Scripts {
        @**@


}

SchoolPortal.Web/Areas/Content/Views/Doc/Index.cshtml
@model IEnumerable<SchoolPortal.Web.Models.Dtos.ClassLevelListDto>
@using SchoolPortal.Web.Areas.Service
@{
    ViewBag.Title = "Index";
}


<div class="row">
    <div class="col-xs-12">
        <div class="box" style="padding:7px;">
            <div class="box-header" style="margin-bottom:15px;">
                <h3 class="box-title" style="font-weight:900;"><i class="fa fa-fw fa-file-text-o"></i> Comprehensive Class List</h3>


                @if (User.IsInRole("SuperAdmin") || User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Other Session", "OtherTerm", "Doc", null, new { @class = "btn btn-primary btn-sm", style = "margin-bottom:5px;" })
                }

                @if (TempData["success"] != null)
                {
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["success"]
                    </div>
                }
                @if (TempData["error"] != null)
                {
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["error"]
                    </div>
                }


            </div>
            <!-- /.box-header -->
            <div class="box-body">

                @foreach (var item in Model)
                {


                    <h3 class="box-title">@item.ClassLevelName</h3>
                    <h5>Form Teacher (@item.FormTeacher)  (@GeneralService.Studentlist(item.Id).Count() @GeneralService.StudentorPupil()<text>s</text>)</h5>
                    <div class="table-responsive">
                        <table id="example1" class="table table-bordered table-hover" border="1">
                            <tr>
                                <th>S/N</th>
                                <th>Username</th>
                                <th>Full Name</th>
                                <th>Registration Number</th>
                                <th>Update</th>
                                @if (User.IsInRole("Admin") || User.IsInRole("SuperAdmin"))
                                {
                                    <th class="noprint">Action</th>
                                }
                            </tr>
                            @{int sno = 0;
                            }
                            @foreach (var students in GeneralService.Studentlist(item.Id).OrderBy(x => x.StudentProfile.user.Surname))
                            {
                                if (GeneralService.Studentlist(item.Id).Count() > 0)
                                {
                                    <tr>
                                        @{ sno++; }

                                        <td>@sno</td>
                                        <td>@students.StudentProfile.user.UserName</td>
                                        <td>@students.StudentProfile.user.Surname @students.StudentProfile.user.FirstName @students.StudentProfile.user.OtherName</td>
                                        <td>@students.StudentProfile.StudentRegNumber</td>
                                        <td>
                                            @if (students.EnableLiveClass == true)
                                            {
                                                @Html.ActionLink("Disable Live Class", "UpdateOnlineData", new { id = students.Id }, new { @class = "noprint" })

                                            }
                                            else
                                            {
                                                @Html.ActionLink("Enable Live Class", "UpdateOnlineData", new { id = students.Id }, new { @class = "noprint" })
                                            }
                                        </td>
                                        @if (User.IsInRole("SuperAdmin") || User.IsInRole("Admin"))
                                        {
                                            <td class="noprint">


                                                <div class="dropdown">
                                                    <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                                        Action
                                                        <span class="caret"></span>
                                                    </button>
                                                    <ul class="dropdown-menu">
                                                        <li>
                                                            @Html.ActionLink("Edit", "EditInfo", new { id = students.StudentProfile.UserId }, new { @class = "noprint" })

                                                        </li>
                                                        <li>
                                                            @Html.ActionLink("Unenroll " + GeneralService.StudentorPupil(), "Removefromsession", "Doc", new { id = students.StudentProfileId }, new { @class = "noprint" })

                                                        </li>
                                                        <li>
                                                            @Html.ActionLink("Move " + GeneralService.StudentorPupil(), "MoveEnrol", "Doc", new { id = students.Id, Ocid = item.Id }, new { @class = "noprint" })

                                                        </li>
                                                        <li>
                                                            @Html.ActionLink("Is Dropout", "Dropout", "Doc", new { id = students.StudentProfileId }, new { @class = "noprint", target="_blank" })

                                                        </li>
                                                        @if (User.IsInRole("SuperAdmin"))
                                                        {

                                                        }

                                                    </ul>
                                                </div>
                                            </td>
                                        }



                                    </tr>
                                }
                                else if (GeneralService.Studentlist(item.Id).Count() < 0)
                                {

                                    <tr>
                                        <th colspan="4" style="text-align:center;">No record Found</th>
                                    </tr>
                                }


                            }
                        </table>
                        <br clear="all" style="page-break-before:always !important;" />
                    </div>

                }

            </div>
            @if (User.IsInRole("SuperAdmin"))
            {
                <a href="@Url.Action("RemoveAllFromCurrentLatest","Doc",new { area ="Content" })" class="btn btn-medium btn-danger remove">Remove all In Term</a>
                @*<a href="@Url.Action("EnrollFromAnotherTermInSession","Doc",new { area ="Content" })" class="btn btn-medium btn-success remove">Enroll From Another Term In Session</a>*@

            }

            @*<div class="box-body">
                <div class="alert bg-danger" style="background-color:#ec121c;color:#ffffff;">
                    @if (User.IsInRole("SuperAdmin"))
                    {
                        <h2 style="border-bottom:1px dotted #ffffff;" class="page-header">DELETE ALL STUDENT IN A TERM</h2>

                        <p> Clicking on the "Remove all In Term" will delete the @GeneralService.StudentorPupil()<span>s</span> in this session and term. Before clicking, please make sure you really want to delete student in that term because this action cannot be reversed.</p><br />


                        <a href="@Url.Action("RemoveAllFromCurrentLatest","Doc",new { area ="Content" })" class="btn btn-medium btn-info remove">Remove all In Term</a>


                    }

                </div>
            </div>*@
        </div>
        <div class="text-center">
            @*<button onclick="myFunction()" style="text-align:center;" class="btn btn-primary">Print</button>*@
            <button onclick="window.print()" style="text-align:center;" class="btn btn-primary">Print</button>

        </div>




        @section Style {

            <link rel="stylesheet" href="http://v1.exwhyzee.ng/admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
        }

        @section Scripts {
            <!-- DataTables -->
            <script src="http://v1.exwhyzee.ng/admin/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
            <script src="http://v1.exwhyzee.ng/admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

        }

        @section Scripts2 {

            <script type="text/javascript">

                //function printSelection(node) {

                //    var content = node.innerHTML
                //    var pwin = window.open('', 'print_content', 'width=800,height=500');

                //    pwin.document.open();
                //    pwin.document.write('<html><body onload="window.print()">' + content + '</body></html>');
                //    pwin.document.close();

                //    setTimeout(function () { pwin.close(); }, 1000);

                //}


                function myFunction() {
                    window.print();
                }


            </script>

            <script>
                $(function () {
                    $('#example1').DataTable()
                    $('#example2').DataTable({
                        'paging': true,
                        'lengthChange': false,
                        'searching': false,
                        'ordering': true,
                        'info': true,
                        'autoWidth': false
                    })
                })
            </script>


            <script type="text/javascript">

                $(document).ready(function () {

                    $('.remove').on('click', function (e, data) {
                        if (!data) {
                            handleRemove(e, 1);
                        } else {
                            window.location = $(this).attr("href");
                        }
                    });
                });


                function handleRemove(e, stop) {
                    if (stop) {
                        e.preventDefault();
                        Swal.fire({
                            title: "Are you sure?",
                            text: "Are you sure you want to delete students/pupils in this term, this action cannot be revert!",
                            type: "warning",
                            showCancelButton: !0,
                            confirmButtonText: "Yes, delete it!",
                            cancelButtonText: "No, cancel!",
                            confirmButtonClass: "btn btn-success mt-2",
                            cancelButtonClass: "btn btn-danger ml-2 mt-2",
                            buttonsStyling: !1
                        }).
                            then(function (t) {
                                t.value ? $(e.target).trigger('click', {}) && Swal.fire({
                                    title: "Deleted!",
                                    text: "Your file has been deleted.",
                                    type: "success",

                                }) : t.dismiss === Swal.DismissReason.cancel && Swal.fire({
                                    title: "Cancelled",
                                    text: "Your Report is safe :)",
                                    type: "error"
                                })
                            })

                    }
                };

            </script>
        }



    </div>
</div>

SchoolPortal.Web/Areas/Content/Views/Doc/MoveClassEnrol.cshtml
@using SchoolPortal.Web.Areas.Service
@{
    ViewBag.Title = "Enroll";
}




<div class="row">
    <!-- left column -->
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <!-- general form elements -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Enroll @GeneralService.StudentorPupil()</h3>
                @if (TempData["error"] != null)
                {
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["error"]
                    </div>
                }
                @if (TempData["success"] != null)
                {
                    <div class="alert alert-success alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
                        @TempData["success"]
                    </div>
                }
            </div>
            <div class="alert bg-danger" style="background-color:#ec121c;color:#ffffff;">
                @if (User.IsInRole("SuperAdmin"))
                {
                    <h2 style="border-bottom:1px dotted #ffffff;" class="page-header">MOVE @GeneralService.StudentorPupil().ToUpper()<span>S</span> TO ANOTHER CLASS</h2>

                    <p> Please Make sure you are not in the term where the @GeneralService.StudentorPupil()<span>s</span> has result previously. Move to the next term if the student has result in the current term that has been published already please.</p><br />
                }

            </div>
            @using (Html.BeginForm("MoveClassEnrol", "Doc", new { id = ViewBag.id }, FormMethod.Post))
            {
                @*@Html.AntiForgeryToken()*@

                <div class="box-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        Class Name
                        <div class="">
                            @Html.DropDownList("ClassLevelId", ViewBag.ClassLevelId as SelectList, "CHOOSE A CLASS", htmlAttributes: new { @class = "form-control" })

                        </div>
                    </div>
                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Enroll @GeneralService.StudentorPupil()</button>
                    <a href="javascript: history.back()" class="btn btn-default">Cancel</a>
                </div>

            }
        </div>

    </div>
    <div class="col-md-3"></div>

</div>



@using SchoolPortal.Web.Areas.Service
@{

    string url = HttpContext.Current.Request.Url.AbsoluteUri;
    Logger.log(User.Identity.Name, url.ToString());

}


@section Scripts {
        @**@
}